### ISSUE TITLE
[Main Branch/Accounts] YouTube layout only works on certain accounts

### ISSUE THREAD

**Issue by disctr4k** [ciulinuwu/cosmic-cat#38]
Big fan of the theme, but the bug I'm currently having is that it doesn't work on my account that I currently use, but works on my older account. When I switch to the theme it automatically goes to my older account and I can't change it back unless if I force sign off of it. Doing so leaves a blank page on my new account. Screenshots below show the current issue.

![image](https://user-images.githubusercontent.com/47229326/179567836-5a09e7d5-a662-4096-83d3-0c131033f1aa.png)
![image](https://user-images.githubusercontent.com/47229326/179567908-3ebff406-3312-4835-bc01-6b2f45ad7cec.png)
![image](https://user-images.githubusercontent.com/47229326/179568635-7891b826-5fcc-4569-9e04-f64c08052b3e.png)

**Comment by aubymori** [comment]
This is probably an issue with brand accounts.

**Comment by disctr4k** [comment]
> 

Yeah I just checked it probably is, I don't want to delete my channel though (turning off brand accounts can affect ur channels)

**Comment by ciulinuwu** [comment]
I will look into this later. Thank you for reporting.

**Comment by Marshadowin** [comment]
Tested on all my brand accounts. Works pretty fine unless its been fixed by now.

**Comment by HastagGuigui** [comment]
Having the same issue, it seems to fetch everything profile-wise from the main google account (profile, channel, subscriptions (on the main youtube page), etc) but then uses the currently logged in account's reccomendations and to check if you're subscribed to the currently watched channel

![image](https://user-images.githubusercontent.com/47950669/183410395-11b5cbe5-b5aa-4b64-b61c-2b20b1bc819a.png)

![image](https://user-images.githubusercontent.com/47950669/183410245-78a4db91-1d0d-42ca-923f-ce453b6d469f.png)

**Comment by darkalexis1990** [comment]
same here .first thanks for the theme its closest to the 2011-12 layout
i hope to fix the following:

1)my channel doesn't load
2)i have to press play in order to video to play it does not auto
3)only the play pause and the volume control works in the progress bar
4)add to.video statistic does not work nothing else works actually :P
5)the comments are NOT loading.

where i can donate? :)

any hope for future to get the ### **_beta cosmic panda_** i loved in my youth? --> 
![image](https://user-images.githubusercontent.com/107497874/186892752-14e36e49-505f-49f9-96bd-2c1e6fecc17d.png)

**Comment by ciulinuwu** [comment]
Has been fixed in Beta 1.0.

I will close this once the beta releases
